name: Publish to Chrome Web Store

on:
  push:
    branches:
      - main 

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: npm install

      - name: Build the extension
        run: pnpm build --zip

      - name: Deploy to Chrome Web Store
        env:
          CLIENT_ID: ${{ secrets.WEBSTORE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.WEBSTORE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.WEBSTORE_REFRESH_TOKEN }}
          APP_ID: ${{ secrets.WEBSTORE_APP_ID }}
        run: |
          npx chrome-webstore-upload-cli upload --source ./dist --target $APP_ID --token-fetch-client-id $CLIENT_ID --token-fetch-client-secret $CLIENT_SECRET --token-fetch-refresh-token $REFRESH_TOKEN
          npx chrome-webstore-upload-cli publish --target $APP_ID --token-fetch-client-id $CLIENT_ID --token-fetch-client-secret $CLIENT_SECRET --token-fetch-refresh-token $REFRESH_TOKEN
